#!/usr/bin/env bash
# scripts/build-macos_app.sh
#
# Build dist/StudyFlow.app — the double-clickable entry point for a local
# install.
#
# Why a bundle and not a .command file
# -----------------------------------
# A .command file opens Terminal.app and leaves the window sitting there after
# the launcher detaches, so the app the user opens has a console window next
# to it. That is not what "local-first" should look like. A bundle avoids it
# three ways at once:
#
#   * macOS runs the executable directly — no Terminal at all.
#   * LSUIElement=true keeps it out of the Dock and out of the app switcher,
#     so the only visible window is the browser that opens.
#   * No icon file means the bundle is a generic script icon in Finder, which
#     is honest: the product icon does not exist yet (see
#     frontend/icons/README.md).
#
# Usage:
#   ./scripts/build-macos_app.sh
#   ./scripts/build-macos_app.sh --open     build, then reveal in Finder
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
APP="$REPO_ROOT/dist/StudyFlow.app"
CONTENTS="$APP/Contents"
EXECUTABLE_NAME="StudyFlow"

if [[ "$(uname -s)" != "Darwin" ]]; then
  echo "error: this bundle is macOS-only. Use: python3 launcher/launch.py" >&2
  exit 1
fi

rm -rf "$APP"
mkdir -p "$CONTENTS/MacOS" "$CONTENTS/Resources"

# ── Info.plist ──────────────────────────────────────────────────────
# CFBundleExecutable points at a shell script, which macOS allows for a
# non-application bundle; the shebang is what the kernel uses to run it.
cat > "$CONTENTS/Info.plist" << 'PLIST'
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>CFBundleName</key>                  <string>StudyFlow</string>
  <key>CFBundleDisplayName</key>           <string>StudyFlow</string>
  <key>CFBundleExecutable</key>             <string>StudyFlow</string>
  <key>CFBundleIdentifier</key>            <string>app.studyflow.pwa.local</string>
  <key>CFBundlePackageType</key>           <string>APPL</string>
  <key>CFBundleShortVersionString</key>    <string>3.0.0</string>
  <key>CFBundleVersion</key>               <string>3.0.0</string>
  <key>LSUIElement</key>                   <true/>
  <key>NSHighResolutionCapable</key>        <true/>
  <key>CFBundleDocumentTypes</key>
  <array>
    <dict>
      <key>CFBundleTypeName</key><string>Folder</string>
      <key>CFBundleTypeRole</key><string>Viewer</string>
      <key>LSItemContentTypes</key>
      <array><string>public.folder</string></array>
    </dict>
  </array>
</dict>
</plist>
PLIST

# ── Executable ──────────────────────────────────────────────────────
# Absolute paths are baked in on purpose: Finder launches a bundle with the
# working directory set to "/", so a relative path would resolve to the root
# filesystem and the launcher would not find itself.
cat > "$CONTENTS/MacOS/$EXECUTABLE_NAME" << LAUNCHER
#!/bin/bash
# Generated by scripts/build-macos_app.sh — edit there, not here.
set -euo pipefail

exec /usr/bin/env python3 "$REPO_ROOT/launcher/launch.py" "\$@"
LAUNCHER
chmod +x "$CONTENTS/MacOS/$EXECUTABLE_NAME"

# ── Stamp it as signed-off ad-hoc, or Gatekeeper quarantines it ─────
# A bundle downloaded in a browser arrives with a quarantine attribute, and an
# unsigned app then refuses to run with an unhelpful dialog. Ad-hoc signing
# keeps a locally-built bundle runnable without a developer certificate.
codesign --force --deep --sign - "$APP" 2>/dev/null \
  || echo "  note: ad-hoc signing unavailable; the bundle still runs locally"

echo "  $APP"
du -sh "$APP" | awk '{print "  tamaño: " $1}'
echo
echo "  Arrancarlo:   open \"$APP\""
echo "  OJO: tras mover o renombrar la app, rehazla con este script —"
echo "       lleva la ruta del repo grabada dentro."

if [[ "${1:-}" == "--open" ]]; then
  open -R "$APP"
fi