"""
Full HTML document template for NotebookLM PDF→HTML conversion.

Wraps body content generated by Gemini in a complete HTML document with
embedded CSS that matches the StudyFlow dark theme.

Exports:
    wrap_html_document(body_html: str) -> str
"""

STUDYFLOW_HTML_CSS = r""":root {
  --bg: #1a1a2e;
  --card: #16213e;
  --border: #0f3460;
  --accent: #e94560;
  --accent2: #533483;
  --text: #eee;
  --muted: #aaa;
  --code-bg: #0d1117;
  --code-text: #7ee787;
  --success: #2ea043;
  --warning: #d29922;
  --info: #58a6ff;
  --table-header: #0f3460;
  --table-alt: #1a1a2e;
  --table-border: #30363d;
}

* { box-sizing: border-box; margin: 0; padding: 0; }

body {
  font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto,
    Helvetica, Arial, sans-serif;
  background-color: var(--bg);
  color: var(--text);
  line-height: 1.7;
  padding: 30px 20px;
  max-width: 900px;
  margin: 0 auto;
}

h1 {
  font-size: 2.2em;
  color: var(--accent);
  border-bottom: 3px solid var(--accent);
  padding-bottom: 12px;
  margin-bottom: 8px;
}

.subtitle {
  color: var(--muted);
  font-style: italic;
  margin-bottom: 30px;
  font-size: 1.05em;
}

h2 {
  font-size: 1.6em;
  color: var(--info);
  margin-top: 45px;
  margin-bottom: 15px;
  padding-left: 10px;
  border-left: 4px solid var(--info);
}

h3 {
  font-size: 1.3em;
  color: #c9a0dc;
  margin-top: 30px;
  margin-bottom: 10px;
}

h4 {
  font-size: 1.1em;
  color: var(--warning);
  margin-top: 20px;
  margin-bottom: 8px;
}

p { margin-bottom: 12px; }

/* ── Intro box ──────────────────────────────────────── */
.intro-box {
  background: linear-gradient(135deg, var(--card), var(--accent2));
  border: 1px solid var(--border);
  border-radius: 10px;
  padding: 20px 25px;
  margin: 20px 0 30px;
}
.intro-box ul { list-style: none; padding: 0; }
.intro-box ul li {
  padding: 5px 0 5px 25px;
  position: relative;
}
.intro-box ul li::before {
  content: "▹";
  position: absolute; left: 5px;
  color: var(--accent); font-weight: bold;
}

/* ── Objectives list ─────────────────────────────────── */
.obj-list {
  list-style: none; padding: 0; counter-reset: obj;
}
.obj-list li {
  counter-increment: obj;
  padding: 8px 0 8px 40px;
  position: relative;
  border-bottom: 1px solid var(--border);
}
.obj-list li::before {
  content: counter(obj);
  position: absolute; left: 5px; top: 8px;
  background: var(--accent); color: #fff;
  width: 26px; height: 26px;
  border-radius: 50%;
  display: flex; align-items: center; justify-content: center;
  font-size: 0.85em; font-weight: bold;
}
.obj-list li strong { color: var(--info); }

/* ── Tables ──────────────────────────────────────────── */
table {
  width: 100%; border-collapse: collapse;
  margin: 15px 0 25px; border-radius: 8px; overflow: hidden;
}
th {
  background-color: var(--table-header);
  color: var(--accent); font-weight: 600;
  text-transform: uppercase; font-size: 0.85em;
  letter-spacing: 0.5px;
}
th, td {
  border: 1px solid var(--table-border);
  padding: 12px 14px; text-align: left;
}
td { background-color: var(--card); }
tr:nth-child(even) td { background-color: var(--table-alt); }
tr:hover td { background-color: var(--border); }

/* ── Code ────────────────────────────────────────────── */
code {
  background-color: var(--code-bg);
  padding: 3px 7px; border-radius: 4px;
  color: var(--code-text);
  font-family: "SF Mono", "Fira Code", "Fira Mono", Menlo, monospace;
  font-size: 0.9em;
  border: 1px solid var(--table-border);
}
pre {
  background-color: var(--code-bg);
  padding: 18px 20px; border-radius: 8px;
  overflow-x: auto; margin: 15px 0 25px;
  border: 1px solid var(--table-border);
}
pre code {
  background: none; border: none; padding: 0;
  font-size: 0.92em; line-height: 1.6;
}

/* ── Callouts ────────────────────────────────────────── */
.note {
  background-color: rgba(88,166,255,0.1);
  border-left: 4px solid var(--info);
  padding: 15px 20px; border-radius: 0 8px 8px 0;
  margin: 20px 0;
}
.note strong { color: var(--info); }

.warning {
  background-color: rgba(210,153,34,0.1);
  border-left: 4px solid var(--warning);
  padding: 15px 20px; border-radius: 0 8px 8px 0;
  margin: 20px 0;
}
.warning strong { color: var(--warning); }

.success {
  background-color: rgba(46,160,67,0.1);
  border-left: 4px solid var(--success);
  padding: 15px 20px; border-radius: 0 8px 8px 0;
  margin: 20px 0;
}
.success strong { color: var(--success); }

/* ── Activity / homework box ─────────────────────────── */
.hw-box {
  background: linear-gradient(135deg, rgba(210,153,34,0.15), rgba(233,69,96,0.1));
  border: 1px solid var(--warning);
  border-radius: 10px; padding: 20px 25px;
  margin: 30px 0;
}
.hw-box strong { color: var(--warning); font-size: 1.1em; }
.hw-box ul { list-style: none; padding: 0; margin-top: 10px; }
.hw-box ul li { padding: 6px 0 6px 28px; position: relative; }
.hw-box ul li::before { content: "📝"; position: absolute; left: 0; }

/* ── Command table (code in tables) ──────────────────── */
.cmd-table code {
  background-color: rgba(126,231,135,0.1);
  color: var(--code-text);
  border-color: rgba(126,231,135,0.2);
}

/* ── TOC ─────────────────────────────────────────────── */
.toc {
  background: var(--card);
  border: 1px solid var(--border);
  border-radius: 10px; padding: 20px 25px;
  margin: 25px 0;
}
.toc h3 { margin-top: 0; color: var(--accent); }
.toc ol { list-style: none; padding: 0; counter-reset: toc; }
.toc ol li { counter-increment: toc; padding: 4px 0; }
.toc ol li::before { content: counter(toc) ". "; color: var(--accent); font-weight: bold; }

/* ── Summary grid ────────────────────────────────────── */
.summary-grid {
  display: grid;
  grid-template-columns: repeat(auto-fit, minmax(180px, 1fr));
  gap: 15px; margin: 20px 0;
}
.summary-card {
  background: var(--card);
  border: 1px solid var(--border);
  border-radius: 8px; padding: 15px; text-align: center;
}
.summary-card .tool {
  font-size: 1.3em; font-weight: bold;
  color: var(--accent);
  font-family: "SF Mono", "Fira Code", monospace;
}
.summary-card .desc {
  font-size: 0.85em; color: var(--muted); margin-top: 5px;
}

/* ── Step list ───────────────────────────────────────── */
.steps { list-style: none; padding: 0; }
.steps li {
  padding: 15px 0 15px 50px; position: relative;
  border-bottom: 1px solid var(--border);
}
.steps li:last-child { border-bottom: none; }
.steps li .step-num {
  position: absolute; left: 5px; top: 15px;
  background: var(--accent2); color: #fff;
  width: 30px; height: 30px; border-radius: 50%;
  display: flex; align-items: center; justify-content: center;
  font-weight: bold; font-size: 0.9em;
}

/* ── Permission visual cards ─────────────────────────── */
.perm-visual {
  display: grid;
  grid-template-columns: repeat(4, 1fr);
  gap: 10px; margin: 15px 0;
}
.perm-card {
  background: var(--card);
  border: 1px solid var(--border);
  border-radius: 8px; padding: 12px; text-align: center;
}
.perm-card .num {
  font-size: 1.8em; font-weight: bold;
  color: var(--accent);
  font-family: "SF Mono", monospace;
}
.perm-card .sym {
  color: var(--code-text);
  font-family: "SF Mono", monospace;
  font-size: 1.1em; margin: 3px 0;
}
.perm-card .desc {
  font-size: 0.78em; color: var(--muted);
}

/* ── UFW examples ────────────────────────────────────── */
.ufw-example {
  display: flex; align-items: flex-start; gap: 10px;
  padding: 10px 0; border-bottom: 1px solid var(--border);
}
.ufw-example:last-child { border-bottom: none; }
.ufw-tag {
  padding: 2px 8px; border-radius: 4px;
  font-size: 0.75em; font-weight: bold;
  text-transform: uppercase; white-space: nowrap;
  min-width: 60px; text-align: center;
}
.ufw-tag.allow {
  background: rgba(46,160,67,0.2);
  color: var(--success); border: 1px solid var(--success);
}
.ufw-tag.deny {
  background: rgba(233,69,96,0.2);
  color: var(--accent); border: 1px solid var(--accent);
}

/* ── Samba config syntax ─────────────────────────────── */
.samba-config {
  background: var(--code-bg);
  padding: 18px 20px; border-radius: 8px;
  margin: 15px 0; border: 1px solid var(--table-border);
}
.samba-config .directive { color: var(--code-text); }
.samba-config .value { color: #f0883e; }
.samba-config .comment { color: #8b949e; }
.samba-config .section { color: var(--accent); }

/* ── Reference section ───────────────────────────────── */
.ref-section {
  background-color: var(--card);
  border: 1px solid var(--border);
  border-radius: 10px; padding: 20px 25px; margin: 20px 0;
}
.ref-section a { color: var(--info); text-decoration: none; }
.ref-section a:hover { text-decoration: underline; }
.ref-section ul { list-style: none; padding: 0; }
.ref-section ul li {
  padding: 5px 0 5px 20px; position: relative;
}
.ref-section ul li::before { content: "📖"; position: absolute; left: 0; }

/* ── Nav links (tags) ────────────────────────────────── */
.nav-links {
  display: flex; flex-wrap: wrap; gap: 8px; margin-top: 15px;
}
.nav-links a {
  color: var(--accent); text-decoration: none;
  padding: 5px 12px;
  border: 1px solid var(--border);
  border-radius: 20px; font-size: 0.85em;
  transition: all 0.2s;
}
.nav-links a:hover { background-color: var(--accent); color: #fff; }
"""


def wrap_html_document(body_html: str, title: str = "StudyFlow") -> str:
    """Wrap a body-content fragment in a full HTML document with StudyFlow CSS.

    Args:
        body_html: HTML fragment to place inside <body>.
        title: Document title for <title> tag.

    Returns:
        Complete HTML document string.
    """
    if not body_html or not body_html.strip():
        return body_html

    # If already a full document, return as-is
    if "</html>" in body_html or "<html" in body_html.lower():
        return body_html

    return f"""<!doctype html>
<html lang="es">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>{title}</title>
    <style>
{STUDYFLOW_HTML_CSS}
    </style>
  </head>
  <body>
{body_html}
  </body>
</html>"""
